//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProdAndonDisp
    {
        public int ProdDashboardID { get; set; }
        public int MachineID { get; set; }
        public System.DateTime CorrectedDate { get; set; }
        public int WOID { get; set; }
        public Nullable<decimal> UtilPercent { get; set; }
        public decimal TotalLoss { get; set; }
        public decimal TotalSetup { get; set; }
        public decimal TotalOperatingTime { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public string Work_Order_No { get; set; }
    
        public virtual tbl_ProdAndonDisp tbl_ProdAndonDisp1 { get; set; }
        public virtual tbl_ProdAndonDisp tbl_ProdAndonDisp2 { get; set; }
        public virtual tblmachinedetail tblmachinedetail { get; set; }
        public virtual tbllivehmiscreen tbllivehmiscreen { get; set; }
    }
}
