//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBreadownAndLossReport
    {
        public int id { get; set; }
        public Nullable<int> breakDownId { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<int> breakDownAndLossCode { get; set; }
        public Nullable<int> machineId { get; set; }
        public string shift { get; set; }
        public Nullable<int> doneWithRow { get; set; }
        public string correctedDate { get; set; }
        public Nullable<System.DateTime> entryTime { get; set; }
        public Nullable<int> messageCodeId { get; set; }
    }
}
