//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPiweb_AdjOEE
    {
        public int id { get; set; }
        public Nullable<int> Machineid { get; set; }
        public string CorrectedDate { get; set; }
        public string AdjOEEuuid { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public int DaystartValue { get; set; }
    }
}
