//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRKSDemo.Server_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuality_Piweb
    {
        public int QualityID { get; set; }
        public string PartNumber { get; set; }
        public Nullable<int> OperationNum { get; set; }
        public Nullable<int> PartIdentity { get; set; }
        public Nullable<int> MachineID { get; set; }
        public string CorrectedDate { get; set; }
        public int IsPiweb { get; set; }
        public Nullable<int> RejectedQty { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public Nullable<int> ApprovedQty { get; set; }
        public string WorkOrderNumber { get; set; }
    }
}
